services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 3m
      start_interval: 0.5s
      interval: 5m
      timeout: 5s
      retries: 5
volumes:
  db:
    driver: local